return {
  'CursorLineNr',
  'LineNrAbove',
  'LineNrBelow',
  'LineNr',
  'Operator',
  'Delimiter',
  'Special', --escape
  '@punctuation.bracket',
  '@punctuation.special.luadoc',
  '@punctuation.bracket.luadoc',
  '@punctuation.bracket.lua',
  '@punctuation.delimiter',
  '@tag.delimiter.html',
  '@tag.xml',
  '@tag',
  '@tag.builtin',
  '@tag.delimiter.vue',
  '@string.regexp',
  '@string.escape',
  '@operator',
  '@keyword.conditional.ternary',
  '@punctuation.bracket.luadoc',
  '@punctuation.special',
  '@punctuation.special.javascript',
  '@constructor.lua',
}
